# Generated by Django 5.2.8 on 2025-11-18 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_country_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='country_code',
            field=models.CharField(default='91', max_length=2),
        ),
    ]
