# Generated by Django 5.2.8 on 2025-11-18 10:22

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('main_image', models.ImageField(upload_to='product_images')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('active', models.BooleanField(default=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.category')),
            ],
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_side', models.ImageField(upload_to='product_images')),
                ('image_back', models.ImageField(upload_to='product_images')),
                ('image_up', models.ImageField(upload_to='product_images')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='products.products')),
            ],
        ),
        migrations.AddIndex(
            model_name='products',
            index=models.Index(fields=['slug'], name='products_pr_slug_9ed2fc_idx'),
        ),
        migrations.AddIndex(
            model_name='products',
            index=models.Index(fields=['price'], name='products_pr_price_55791d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='products',
            unique_together={('name', 'category')},
        ),
    ]
