# Generated by Django 5.2.8 on 2025-12-22 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_rename_category_name_category_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='name',
            new_name='category_name',
        ),
    ]
