# Generated by Django 5.2.8 on 2025-12-22 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_rename_name_category_category_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='main_image',
        ),
        migrations.AddField(
            model_name='productimage',
            name='main_image',
            field=models.ImageField(blank=True, null=True, upload_to='product_images'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image_back',
            field=models.ImageField(blank=True, null=True, upload_to='product_images'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image_side',
            field=models.ImageField(blank=True, null=True, upload_to='product_images'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image_up',
            field=models.ImageField(blank=True, null=True, upload_to='product_images'),
        ),
    ]
