# Generated by Django 5.2.8 on 2025-12-22 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_remove_products_main_image_productimage_main_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productimage',
            old_name='image_back',
            new_name='back_image',
        ),
        migrations.RenameField(
            model_name='productimage',
            old_name='image_side',
            new_name='side_image',
        ),
        migrations.RenameField(
            model_name='productimage',
            old_name='image_up',
            new_name='up_image',
        ),
    ]
