# Generated by Django 5.2.8 on 2025-12-22 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_rename_image_back_productimage_back_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productimage',
            old_name='back_image',
            new_name='image_back',
        ),
        migrations.RenameField(
            model_name='productimage',
            old_name='side_image',
            new_name='image_side',
        ),
        migrations.RenameField(
            model_name='productimage',
            old_name='up_image',
            new_name='image_up',
        ),
    ]
